-- MySQL Script generated by MySQL Workbench
-- Sat Nov  2 23:06:52 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbPizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbPizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbPizzeria` DEFAULT CHARACTER SET utf8 ;
USE `dbPizzeria` ;

-- -----------------------------------------------------
-- Table `dbPizzeria`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbPizzeria`.`Persona` (
  `CI` VARCHAR(20) NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`CI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbPizzeria`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbPizzeria`.`Cliente` (
  `Cuenta` VARCHAR(20) NOT NULL,
  `Codigo` INT(50) NULL,
  `CI` VARCHAR(20) NULL,
  PRIMARY KEY (`Cuenta`),
  -- INDEX `fk_Cliente_Persona_idx` (`CI` ASC) INVISIBLE,
  CONSTRAINT `fk_Cliente_Persona`
    FOREIGN KEY (`CI`)
    REFERENCES `dbPizzeria`.`Persona` (`CI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbPizzeria`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbPizzeria`.`Usuario` (
  `Cod_Usuario` INT(50) NOT NULL,
  `Usuario` VARCHAR(50) NULL,
  `Contrasena` VARCHAR(50) NULL,
  `Direccion` VARCHAR(250) NULL,
  `CI` VARCHAR(20) NULL,
  PRIMARY KEY (`Cod_Usuario`),
  -- INDEX `fk_Usuario_Persona_idx` (`CI` ASC) INVISIBLE,
  CONSTRAINT `fk_Usuario_Persona`
    FOREIGN KEY (`CI`)
    REFERENCES `dbPizzeria`.`Persona` (`CI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbPizzeria`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbPizzeria`.`Pedido` (
  `NumPedido` INT(11) NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NULL,
  `Total` DOUBLE NULL,
  `Cod_Usuario` INT(50) NULL,
  `Cuenta` VARCHAR(20) NULL,
  PRIMARY KEY (`NumPedido`),
  -- INDEX `fk_Pedido_Cliente_idx` (`Cuenta` ASC) INVISIBLE,
  -- INDEX `fk_Pedido_Usuario_idx` (`Cod_Usuario` ASC) INVISIBLE,
  CONSTRAINT `fk_Pedido_Cliente`
    FOREIGN KEY (`Cuenta`)
    REFERENCES `dbPizzeria`.`Cliente` (`Cuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Usuario`
    FOREIGN KEY (`Cod_Usuario`)
    REFERENCES `dbPizzeria`.`Usuario` (`Cod_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbPizzeria`.`Pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbPizzeria`.`Pizza` (
  `Cod_Pz` INT(11) NOT NULL,
  `PNombre` VARCHAR(50) NULL,
  `Precio` DOUBLE NULL,
  `Descripcion` VARCHAR(250) NULL,
  `Tam` VARCHAR(50) NULL,
  PRIMARY KEY (`Cod_Pz`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbPizzeria`.`Detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbPizzeria`.`Detalle` (
  `Cod_Pz` INT(11) NULL AUTO_INCREMENT,
  `NumPedido` INT(11) NULL,
  `SubTotal` DOUBLE NULL,
  -- INDEX `fk_detalle_Pedido_idx` (`NumPedido` ASC) INVISIBLE,
  CONSTRAINT `fk_detalle_Pedido`
    FOREIGN KEY (`NumPedido`)
    REFERENCES `dbPizzeria`.`Pedido` (`NumPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_Pizza`
    FOREIGN KEY (`Cod_Pz`)
    REFERENCES `dbPizzeria`.`Pizza` (`Cod_Pz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
